WIDTH = 640
HEIGHT = 400
SIZE = (WIDTH, HEIGHT)

CLOSE_TILE_SIZE = (80,80)
CLOUD_TILE_SIZE = (50,50)
DISTANT_TILE_SIZE = (40,40)
OBSTACLE_TILE_SIZE = (45, 45)
DONUT_TILE_SIZE = (30, 30)

BACKGROUND_SPEED = 0.25
FOREGROUND_SPEED = 6
FOREGROUND_SPEED_MEDIUM = 8
FOREGROUND_SPEED_FAST = 10

SPEED = FOREGROUND_SPEED
SPEEDS = [FOREGROUND_SPEED, FOREGROUND_SPEED_MEDIUM, FOREGROUND_SPEED_FAST]

COLOUR_PINK = (255, 161, 183)
COLOUR_YELLOW = (242, 231, 157)
COLOUR_BLUE = (173, 216, 230)

COLOUR = COLOUR_PINK
COLOURS = [COLOUR_PINK, COLOUR_YELLOW, COLOUR_BLUE]

#----------------------------------------

CHARACTER = ["spoon.png", "fork.png", "knife.png"]